# Generated by Django 4.0.5 on 2022-06-16 12:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0002_companyacceptance'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.CharField(max_length=12)),
                ('user_technology', models.CharField(max_length=30)),
                ('user_12th_marks', models.FloatField()),
                ('user_10th_marks', models.FloatField()),
                ('user_CPI', models.FloatField()),
                ('user_CV', models.FileField(upload_to='CV/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])])),
                ('accepted_status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
