# Generated by Django 4.0.5 on 2022-06-17 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0005_interviewertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewer_phone', models.CharField(max_length=12)),
                ('interviewer_technology', models.CharField(max_length=30)),
                ('job_role', models.CharField(max_length=30)),
                ('Experience', models.CharField(max_length=30)),
                ('interviewer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_login.userdetails')),
                ('type_interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_login.interviewertype')),
            ],
        ),
    ]
