# Generated by Django 4.0.5 on 2022-06-17 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0006_interviewerdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewerdetails',
            name='interviewer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
