# Generated by Django 4.0.5 on 2022-06-20 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0008_userjobapplied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userjobapplied',
            name='company',
        ),
        migrations.AddField(
            model_name='userjobapplied',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='user_login.jobopenings'),
        ),
    ]
