# Generated by Django 4.0.5 on 2022-06-20 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0009_remove_userjobapplied_company_userjobapplied_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewercompany',
            name='interviewer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userjobapplied',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='user_login.jobopenings'),
        ),
    ]
