# Generated by Django 4.0.5 on 2022-06-23 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0010_alter_interviewercompany_interviewer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_round', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Scheduled', 'Scheduled')], default='Pending', max_length=15)),
                ('HR_round', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Scheduled', 'Scheduled')], default='Pending', max_length=15)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_login.userjobapplied')),
            ],
        ),
    ]
