# Generated by Django 4.0.5 on 2022-06-23 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0011_userinterview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterview',
            name='job_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_login.userjobapplied'),
        ),
    ]
