# Generated by Django 4.0.5 on 2022-06-24 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0012_alter_userinterview_job_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('interview_time', models.CharField(choices=[('09:00 – 09:30', '09:00 – 09:30'), ('10:00 – 10:30', '10:00 – 10:30'), ('11:00 – 11:30', '11:00 – 11:30'), ('12:00 – 12:30', '12:00 – 12:30'), ('13:00 – 13:30', '13:00 – 13:30'), ('14:00 – 14:30', '14:00 – 14:30'), ('15:00 – 15:30', '15:00 – 15:30'), ('16:00 – 16:30', '16:00 – 16:30'), ('17:00 – 17:30', '17:00 – 17:30')], max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_login.userinterview')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_login.interviewerdetails')),
                ('type_interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_login.interviewertype')),
            ],
        ),
    ]
