# Generated by Django 4.0.5 on 2022-06-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0013_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interview_time',
            field=models.CharField(choices=[('09:00–09:30', '09:00–09:30'), ('10:00–10:30', '10:00–10:30'), ('11:00–11:30', '11:00–11:30'), ('12:00–12:30', '12:00–12:30'), ('13:00–13:30', '13:00–13:30'), ('14:00–14:30', '14:00–14:30'), ('15:00–15:30', '15:00–15:30'), ('16:00–16:30', '16:00–16:30'), ('17:00–17:30', '17:00-17:30')], max_length=20),
        ),
    ]
