# Generated by Django 4.0.5 on 2022-06-28 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0015_userfeedback_notification_interviewerfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='RescheduleRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.IntegerField()),
                ('reason', models.CharField(max_length=300)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_login.userinterview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
