# Generated by Django 4.0.5 on 2022-06-28 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0016_reschedulerequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_login.userinterview'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='marks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='examiner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Examiner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='feedback',
            field=models.CharField(default='You are good enough but you need little bit improvement', max_length=300),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
