# Generated by Django 4.0.5 on 2022-06-28 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0017_userfeedback_application_userfeedback_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewerfeedback',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Interviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
