# Generated by Django 4.0.5 on 2022-07-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0018_alter_interviewerfeedback_interviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_block',
            field=models.BooleanField(default=False),
        ),
    ]
