# Generated by Django 4.0.5 on 2022-07-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0019_customuser_is_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_activated',
            field=models.BooleanField(default=True),
        ),
    ]
