# Generated by Django 4.0.5 on 2022-07-07 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0021_blockuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reschedulerequests',
            name='application',
        ),
        migrations.RemoveField(
            model_name='reschedulerequests',
            name='interview_type',
        ),
        migrations.AddField(
            model_name='reschedulerequests',
            name='interview_application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Interview_Id', to='user_login.interview'),
        ),
    ]
