# Generated by Django 4.0.5 on 2022-07-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0023_reschedulerequests_is_rescheduled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='accepted_status',
            field=models.BooleanField(null=True),
        ),
    ]
