# Generated by Django 4.0.5 on 2022-07-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0024_alter_userdetails_accepted_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterview',
            name='selection_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
