# Generated by Django 4.0.5 on 2022-07-19 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0025_userinterview_selection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_CV',
            field=models.FileField(default='CV/default.pdf', upload_to='CV/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])]),
        ),
    ]
