# Generated by Django 4.0.5 on 2022-07-19 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0026_alter_userdetails_user_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_10th_marks',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user_12th_marks',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user_CPI',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
